### ISSUE TITLE
Does this work with Mautic 3?

### ISSUE THREAD

**Issue by connectedbusiness-gary** [Logicify/mautic-advanced-templates-bundle#18]
running Mautic 3 and cannot get the plugin to show. Am i doing something wrong or does this not work with Mautic 3 yet...

**Comment by jordan8037310** [comment]
Following...

**Comment by stevedrobinson** [comment]
Following...

**Comment by incentfit** [comment]
I can confirm that this plugin is completely broken on Mautic 3.1

**Comment by connectedbusiness-gary** [comment]
i can confirm that this one works in M3.1 

https://mtcextendee.com/marketplace/twig-templates-for-mautic/

**Comment by benfavre** [comment]
in : plugins/MauticAdvancedTemplatesBundle/EventListener/EmailSubscriber.php

Change :
`use Mautic\CampaignBundle\Entity\Lead;
// use Mautic\CoreBundle\EventListener\CommonSubscriber;`

`/**
 * Class EmailSubscriber.
 */
class EmailSubscriber implements EventSubscriberInterface`

`public function onEmailGenerate(Events\EmailSendEvent $event)
    {
        // $this->logger->info('onEmailGenerate MauticAdvancedTemplatesBundle\EmailSubscriber');
        $content = $event->getContent();
        $content = $this->templateProcessor->processTemplate($content,  $event->getLead());
        $event->setContent($content);
        if ( empty( trim($event->getPlainText()) ) ) {
            $event->setPlainText( (new PlainTextHelper($content))->getText() );
        }
    }`

**Comment by stvhanna** [comment]
@colethorsen Tested and confirmed your PR works with v3.

**Comment by MarketSmart** [comment]
Closing this issue in favor of skipping over to mautic 4
