### ISSUE TITLE
Twig for SMS

### ISSUE THREAD

**Issue by bobsburgers** [Logicify/mautic-advanced-templates-bundle#21]
Working on getting this to work with sms sends as well. So far it seems doable. 

Wanted to check if this impossible, really hard or already in progress.

**Comment by stvhanna** [comment]
Hi @bobsburgers Any updates on this?

**Comment by bobsburgers** [comment]
> 
> 
> Hi @bobsburgers Any updates on this?

Yep i did this pull 
https://github.com/Logicify/mautic-advanced-templates-bundle/pull/22
