### ISSUE TITLE
Need Help, Its Not Working for Me

### ISSUE THREAD

**Issue by imlolman** [Logicify/mautic-advanced-templates-bundle#33]
I am having trouble with the "Mautic Advanced Templates Bundle" plugin in my Mautic instance. I have installed the plugin and followed the instructions, but I am still encountering issues.

**Mautic Version:** v4.1.2
**PHP: 7.4**

Steps taken so far:

- Installed and Activated the "Mautic Advanced Templates Bundle" plugin.
- Created a new Email Template, edited in source code mode.
- Sent the Email.
- Didn't Received the required result

Screenshots:
Template Code:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/11874560/230748001-6ab5ebf4-cfb3-4ed3-a990-f6dea62ae494.png">

Received In Email:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/11874560/230748007-1bff530d-a98c-471c-b9dd-f36229fa3cdf.png">

**Comment by imlolman** [comment]
Very Sorry, There was a mistake from my side.

Thankyou very much for this plugin.

**Comment by zeroggdr** [comment]
I'm experiencing this same issue. What did you do to solve this? @imlolman
