### ISSUE TITLE
Mautic doesn't recognize the plugin if you just clone it

### ISSUE THREAD

**Issue by pjeby** [Logicify/mautic-advanced-templates-bundle#4]
I was not able to get my Mautic installation to recognize the plugin until I renamed the directory fro `mautic-advanced-templates-bundle` to `MauticAdvancedTemplatesBundle`.  It would be good to mention this in the documentation, or perhaps to change the name of the repository so that cloning it will work correctly by default.

**Comment by corvis** [comment]
Mentioned it under installation section, thanks.
