### ISSUE TITLE
Same value for different contacts in campaign batch

### ISSUE THREAD

**Issue by zero-one-devteam** [Logicify/mautic-advanced-templates-bundle#6]
It looks the twig expression result value from the email template for the first contact in campaign is repeated for every contact in a campaign (e.g. lastname - each contact gets the same lastname)

To reproduce:

1. Create email template with Twig expression extracting data from contact/lead
{% TWIG_BLOCK %} 
    <p>Hi {{lead.firstname}},</p>    
{% END_TWIG_BLOCK %}
2. Select segment with more than 1 contact
3. Start campaign

-> each contact gets an email with the lastnameof the first contact

**Comment by silvermind** [comment]
Had the same issue and just sent out a bad Campaign. It seems like the TWIG_BLOCK is only evaluated once per campaign mailing, did you test if it work when using a Code Snippet? https://github.com/Logicify/mautic-advanced-templates-bundle#example-3-reusable-code-snippets It works nicely in form mails..

**Comment by oytuntez** [comment]
hmm, this is a deal-breaker, no? did anyone achieve campaign emailing with this plugin bundle?

**Comment by benfavre** [comment]
`{{ "{% TWIG_BLOCK %}" }}
{{ "{% set posts = 'https://xxx.yyy/feed' | rss %}" }}
{{ "{% END_TWIG_BLOCK %}" }}`

**Comment by kuzmany** [comment]
Hi guys, can you test https://github.com/Logicify/mautic-advanced-templates-bundle/pull/10 ?

**Comment by corvis** [comment]
This PR has been merged into master and included into release 1.1. Thanks, @kuzmany
