### ISSUE TITLE
TWIG_BLOCK unknown

### ISSUE THREAD

**Issue by leosuganob** [Logicify/mautic-advanced-templates-bundle#8]
**Mautic Version:** 2.15.1
**PHP Version:** 7.0.18

This seems working on Email Template creation through 'Code Mode' option. But when I tried to applied it on the theme that I created, it breaks. I got this error:

mautic.CRITICAL: Uncaught PHP Exception Twig_Error_Syntax: "Unknown "TWIG_BLOCK" tag." at /var/www/html/mautic/themes/hp-transactional/html/email.html.twig line 90 {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"TWIG_BLOCK\" tag. at /var/www/html/mautic/themes/hp-transactional/html/email.html.twig:90)"} []

**Comment by benfavre** [comment]
You have to create a template like this
````
{{ "{% TWIG_BLOCK %}" }}
{{ "{% set posts = 'https://xxx.yyy/feed' | rss %}" }}
.....
{{ "{% END_TWIG_BLOCK %}" }}
````
